baseURL = "https://heige-pcloud.github.io/example/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "dre4merp's blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "归档"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "关于我"
    url = "/about/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "subscription"
    pre = ""
    post = ""
    name = "订阅"
    url = "/index.xml"
    title = ""
    weight = 5

[params]
  #  DoIt 主题版本
  version = "0.4.X"
  # 网站名称
  title = "dre4merp's blog"
  # 网站描述
  description = "This is dre4merp's blog."
  # 网站关键词
  keywords = ["CyberSecurity", "C++", "Java"]
  #  网站默认主题样式 ("light", "dark", "black", "auto")
  defaultTheme = "auto"
  # 公共 git 仓库路径, 仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""
  #  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  #  日期格式
  dateFormat = "2006-01-02"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]
  #  开启 PWA 支持
  enablePWA = false
  # [试验性功能] 缓存markdown中的图片链接到本地，详情请见：https://github.com/HEIGE-PCloud/DoIt/pull/860#issue-1574342372
  cacheRemoteImages = true
  # [试验性功能] 使用 hugo 自带的图片处理功能生成 srcset 属性
  optimizeImages = true
  # [实验性功能] optimizeImages 中 srcset 属性的缩放方法, 详情请见：https://gohugo.io/content-management/image-processing/#image-processing-options
  srcsetSmallResizeMethod = "700x webp Lanczos q75"
  srcsetDefaultResizeMethod = "1200x webp Lanczos q75"
  srcsetLargeResizeMethod = "2000x webp Lanczos q75"
  #  版权信息
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # 作者配置
  [params.author]
    name = "dre4merp"
    email = "dre4merp@gmail.com"
    link = "https://github.com/dre4merp"
    avatar = "/images/avatar.webp"
    gravatarEmail = "dre4merp@gmail.com"
  
  # 页面底部信息配置
  [params.footer]
    enable = true
    #  自定义内容 (支持 HTML 格式)
    custom = 'dre4merp is trying harder.'
    #  是否显示 Hugo 和主题信息
    hugo = true
    #  托管服务信息 (支持 HTML 格式)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
    hostedOn = ''
    #  是否显示版权信息
    copyright = true
    #  是否显示作者
    author = true
    # 网站创立年份
    since = 2019
    # ICP 备案信息, 仅在中国使用 (支持 HTML 格式)
    icp = ""
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  
  # 主页配置
  [params.home]
    #  RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱, 用于优先在主页显示的头像
      gravatarEmail = "dre4merp@gmail.com"
      # 主页显示头像的 URL
      # 将你的头像文件放置于 static 或者 assets 目录下
      # 文件路径是相对于 static 或者 assets 目录的
      avatarURL = "/images/avatar.webp"
      # 头像的链接指向的 URL
      avatarLinkURL = ""
      #  主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题
      subtitle = "This is dre4merp's blog."
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      #  免责声明 (支持 HTML 格式)
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
      #  被 params.page 中的 hiddenFromHomePage 替代
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

  # 作者的社交信息设置
  [params.social]
    GitHub = "dre4merp"
    Email = "dre4merp@gmail.com"
    RSS = true # DoIt 新增 | 0.2.0


  # DoIt 更改 | 0.2.0 文章页面配置
  [params.page]
    # DoIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # DoIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # DoIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = true
    # DoIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # DoIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = false
    # DoIt 新增 | 0.2.14 配置文章原始文件的链接
    linkToSource = false
    # "https://github.com/user/repo/blob/main/{path}"
    # DoIt 新增 | 0.2.13 配置编辑文章的链接
    linkToEdit = false
    # "https://github.com/user/repo/edit/main/{path}"
    # "https://gitlab.com/user/repo/-/edit/main/{path}"
    # "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
    # DoIt 新增 | 0.2.14 配置提交错误的链接
    linkToReport = false
    # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
    # DoIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # DoIt 新增 | 0.2.13 是否在文章开头显示系列导航
    seriesNavigation = true
    # 是否启用最后修改时间
    enableLastMod = true
    # 是否启用字数统计
    enableWordCount = true
    # 是否启用阅读时间估计
    enableReadingTime = true
    # DoIt 新增 | 0.2.13 过时文章提示
    [params.page.outdatedArticleReminder]
      enable = true
      # 如果文章最后更新于 90 天之前，显示提醒
      reminder = 90
      # 如果文章最后更新于 180 天之前，显示警告
      warning = 180
    # DoIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
    # DoIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 默认展开显示的代码行数
      maxShownLines = 10
    # DoIt 新增 | 0.2.14 表格配置
    [params.page.table]
      # 是否开启表格排序
      sort = true
    # DoIt 更改 | 0.2.0 KaTeX 数学公式
    [params.page.math]
      enable = true
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
      # 使用 MathJax 替代 KaTeX
      mathjax = false
    # DoIt 新增 | 0.2.0 Mapbox GL JS 配置
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # DoIt 更改 | 0.2.0 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
      Mastodon = false

    # instant.page 设置
    [params.page.instantpage]
      enable = false

    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # DoIt 新增 | 0.2.14 更多第三方库配置
        # [params.page.library.css.someOtherCSS]
        #   src = "someOther.css"
        #   defer = true
        #   attr = "customAttribute"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavaScript = "some.js"
        # DoIt 新增 | 0.2.14 更多第三方库配置
        # [params.page.library.js.someOtherJavaScript]
        #   src = "someOther.js"
        #   defer = false
        #   async = true
        #   attr = "customAttribute"
        # 位于 "assets/"
        # 或者
        # someJavaScript = "https://cdn.example.com/some.js"
    # DoIt 更改 | 0.2.10 页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = "dre4merp"
        logoUrl = ""
    # DoIt 新增 | 0.2.14 相关文章推荐配置
    [params.page.related]
      enable = true
      count = 5


  # DoIt 新增 | 0.2.13 赞赏配置
  [params.sponsor]
    enable = false
    bio = "如果你觉得这篇文章对你有所帮助，欢迎赞赏~"
    link = "https://www.buymeacoffee.com" # 你的赞赏页面的地址
    custom = "" # 自定义 HTML
  
  #  网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""
    # 
    # Google 搜索结果中网站备用名字
    alternateName = ["dre4merp blog"]

  #  网站分析配置
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-KDR7NTQEPH"
      # 是否匿名化用户 IP
      anonymizeIP = true

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置
[Permalinks]
  posts = ":year/:month/:filename"
  # posts = ":filename"
  
# 用于 Hugo 输出文档的设置
[outputs]
  # 
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# 用于分类的设置
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

[server]
  [server.render]
    timeout = "60s"
